-- =============================================================================
-- SQL PARA CONFIGURAR EL MODULO DE BODEGAS EN SUPABASE
-- =============================================================================

-- 1. Crear tablas si no existen
CREATE TABLE IF NOT EXISTS bodegas_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    excel_unique_id TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL,
    unit TEXT DEFAULT 'UND',
    current_stock NUMERIC DEFAULT 0,
    min_stock NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bodegas_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT REFERENCES bodegas_inventory(id) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('IN', 'OUT')),
    quantity NUMERIC NOT NULL CHECK (quantity > 0),
    date DATE DEFAULT CURRENT_DATE,
    reason TEXT,
    created_by_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Migrar columnas nuevas (si la tabla ya existe con columnas viejas)
DO $$
BEGIN
    -- bodegas_inventory: renombrar category -> bodega
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'category') THEN
        ALTER TABLE bodegas_inventory RENAME COLUMN category TO bodega;
    END IF;

    -- bodegas_inventory: agregar columnas nuevas
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'excel_unique_id') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN excel_unique_id TEXT;
        CREATE UNIQUE INDEX IF NOT EXISTS idx_bodegas_inventory_excel_unique_id ON bodegas_inventory(excel_unique_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'specifications') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN specifications TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'initial_stock') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN initial_stock NUMERIC DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'location') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN location TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'bodega') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN bodega TEXT;
    END IF;

    -- bodegas_transactions: agregar columnas nuevas
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'time') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN time TIME;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'bodega') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN bodega TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'specifications') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN specifications TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'received_by') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN received_by TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'dispatched_by') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN dispatched_by TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'voucher_code') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN voucher_code TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'notes') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN notes TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'location') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN location TEXT;
    END IF;

    -- Eliminar columna reason si existe (reemplazada por notes)
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'reason') THEN
        ALTER TABLE bodegas_transactions DROP COLUMN reason;
    END IF;
END
$$;

-- 3. Funcion para actualizar stock automaticamente
CREATE OR REPLACE FUNCTION update_inventory_stock()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        IF (NEW.type = 'IN') THEN
            UPDATE bodegas_inventory SET current_stock = current_stock + NEW.quantity, updated_at = NOW() WHERE id = NEW.item_id;
        ELSIF (NEW.type = 'OUT') THEN
            UPDATE bodegas_inventory SET current_stock = current_stock - NEW.quantity, updated_at = NOW() WHERE id = NEW.item_id;
        END IF;
    ELSIF (TG_OP = 'UPDATE') THEN
        IF (OLD.type = 'IN') THEN
            UPDATE bodegas_inventory SET current_stock = current_stock - OLD.quantity, updated_at = NOW() WHERE id = OLD.item_id;
        ELSIF (OLD.type = 'OUT') THEN
            UPDATE bodegas_inventory SET current_stock = current_stock + OLD.quantity, updated_at = NOW() WHERE id = OLD.item_id;
        END IF;
        IF (NEW.type = 'IN') THEN
            UPDATE bodegas_inventory SET current_stock = current_stock + NEW.quantity, updated_at = NOW() WHERE id = NEW.item_id;
        ELSIF (NEW.type = 'OUT') THEN
            UPDATE bodegas_inventory SET current_stock = current_stock - NEW.quantity, updated_at = NOW() WHERE id = NEW.item_id;
        END IF;
    ELSIF (TG_OP = 'DELETE') THEN
        IF (OLD.type = 'IN') THEN
            UPDATE bodegas_inventory SET current_stock = current_stock - OLD.quantity, updated_at = NOW() WHERE id = OLD.item_id;
        ELSIF (OLD.type = 'OUT') THEN
            UPDATE bodegas_inventory SET current_stock = current_stock + OLD.quantity, updated_at = NOW() WHERE id = OLD.item_id;
        END IF;
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Trigger
DROP TRIGGER IF EXISTS tr_update_stock ON bodegas_transactions;
CREATE TRIGGER tr_update_stock
AFTER INSERT OR UPDATE OR DELETE ON bodegas_transactions
FOR EACH ROW
EXECUTE FUNCTION update_inventory_stock();

-- 5. Indices (despues de migrar columnas)
CREATE INDEX IF NOT EXISTS idx_bodegas_inventory_code ON bodegas_inventory(code);
CREATE INDEX IF NOT EXISTS idx_bodegas_inventory_bodega ON bodegas_inventory(bodega);
CREATE INDEX IF NOT EXISTS idx_bodegas_transactions_item_id ON bodegas_transactions(item_id);
CREATE INDEX IF NOT EXISTS idx_bodegas_transactions_type ON bodegas_transactions(type);
CREATE INDEX IF NOT EXISTS idx_bodegas_transactions_date ON bodegas_transactions(date);

-- 6. RLS
ALTER TABLE bodegas_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodegas_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON bodegas_inventory;
DROP POLICY IF EXISTS "Enable read access for all users" ON bodegas_transactions;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON bodegas_inventory;
DROP POLICY IF EXISTS "Enable all for authenticated users" ON bodegas_transactions;

CREATE POLICY "Enable read access for all users" ON bodegas_inventory FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON bodegas_transactions FOR SELECT USING (true);
CREATE POLICY "Enable all for authenticated users" ON bodegas_inventory FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for authenticated users" ON bodegas_transactions FOR ALL USING (true) WITH CHECK (true);

-- 7. Verificacion
SELECT 'bodegas_inventory columns:' as info;
SELECT column_name, data_type FROM information_schema.columns
WHERE table_name = 'bodegas_inventory' ORDER BY ordinal_position;

SELECT 'bodegas_transactions columns:' as info;
SELECT column_name, data_type FROM information_schema.columns
WHERE table_name = 'bodegas_transactions' ORDER BY ordinal_position;