-- =============================================================================
-- SQL PARA CONFIGURAR EL MODULO DE BODEGAS EN SUPABASE (v3.0)
-- Optimizado con mejores practicas de Supabase Postgres
-- =============================================================================
-- Ejecutar en SQL Editor de Supabase
-- Para recarga limpia: descomentar la seccion 0 antes de ejecutar
-- =============================================================================

-- =============================================================================
-- 0. RECARGA LIMPIA (descomentar para limpiar datos existentes)
-- =============================================================================
-- TRUNCATE bodegas_transactions RESTART IDENTITY CASCADE;
-- TRUNCATE bodegas_inventory RESTART IDENTITY CASCADE;
-- TRUNCATE bodegas_list RESTART IDENTITY CASCADE;

-- =============================================================================
-- 1. TABLAS PRINCIPALES
-- =============================================================================

CREATE TABLE IF NOT EXISTS bodegas_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    excel_unique_id TEXT NOT NULL,
    description TEXT NOT NULL,
    specifications TEXT,
    unit TEXT NOT NULL DEFAULT 'UND',
    initial_stock NUMERIC NOT NULL DEFAULT 0,
    current_stock NUMERIC NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    min_stock NUMERIC NOT NULL DEFAULT 0,
    bodega TEXT,
    location TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bodegas_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES bodegas_inventory(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('IN', 'OUT')),
    quantity NUMERIC NOT NULL CHECK (quantity > 0),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    time TIME,
    bodega TEXT,
    specifications TEXT,
    received_by TEXT,
    dispatched_by TEXT,
    voucher_code TEXT,
    location TEXT,
    notes TEXT,
    created_by_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bodegas_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 2. MIGRACION DE COLUMNAS (para esquemas existentes)
-- =============================================================================

DO $$
BEGIN
    -- bodegas_inventory
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'category' AND column_name != 'bodega') THEN
        ALTER TABLE bodegas_inventory RENAME COLUMN category TO bodega;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'excel_unique_id') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN excel_unique_id TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'specifications') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN specifications TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'initial_stock') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN initial_stock NUMERIC DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'location') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN location TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_inventory' AND column_name = 'bodega') THEN
        ALTER TABLE bodegas_inventory ADD COLUMN bodega TEXT;
    END IF;

    -- bodegas_transactions
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'time') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN time TIME;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'bodega') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN bodega TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'specifications') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN specifications TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'received_by') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN received_by TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'dispatched_by') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN dispatched_by TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'voucher_code') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN voucher_code TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'notes') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN notes TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'location') THEN
        ALTER TABLE bodegas_transactions ADD COLUMN location TEXT;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bodegas_transactions' AND column_name = 'reason') THEN
        ALTER TABLE bodegas_transactions DROP COLUMN reason;
    END IF;
END
$$;

-- =============================================================================
-- 3. INDICES (optimizados con indices parciales)
-- =============================================================================

-- Unique constraint para excel_unique_id
CREATE UNIQUE INDEX IF NOT EXISTS idx_bodegas_inventory_excel_unique_id
    ON bodegas_inventory(excel_unique_id);

-- Busqueda por codigo y bodega (consulta mas comun)
CREATE INDEX IF NOT EXISTS idx_bodegas_inventory_code ON bodegas_inventory(code);
CREATE INDEX IF NOT EXISTS idx_bodegas_inventory_bodega ON bodegas_inventory(bodega);

-- Indice compuesto para busquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_bodegas_inventory_bodega_code
    ON bodegas_inventory(bodega, code);

-- Transacciones: indice por item_id (FK lookup)
CREATE INDEX IF NOT EXISTS idx_bodegas_transactions_item_id ON bodegas_transactions(item_id);

-- Indices parciales para tipos de transaccion (mejor rendimiento)
CREATE INDEX IF NOT EXISTS idx_bodegas_transactions_type_in
    ON bodegas_transactions(date, item_id) WHERE type = 'IN';
CREATE INDEX IF NOT EXISTS idx_bodegas_transactions_type_out
    ON bodegas_transactions(date, item_id) WHERE type = 'OUT';

-- Indice por fecha para consultas de rango
CREATE INDEX IF NOT EXISTS idx_bodegas_transactions_date ON bodegas_transactions(date DESC);

-- Indice compuesto para filtros por bodega + fecha
CREATE INDEX IF NOT EXISTS idx_bodegas_transactions_bodega_date
    ON bodegas_transactions(bodega, date DESC);

-- Bodegas list
CREATE INDEX IF NOT EXISTS idx_bodegas_list_name ON bodegas_list(name);

-- =============================================================================
-- 4. TRIGGER: Actualizacion automatica de stock
-- =============================================================================

CREATE OR REPLACE FUNCTION update_inventory_stock()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE bodegas_inventory
        SET current_stock = current_stock +
                CASE WHEN NEW.type = 'IN' THEN NEW.quantity ELSE -NEW.quantity END,
            updated_at = NOW()
        WHERE id = NEW.item_id;
        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN
        -- Revertir efecto del valor anterior
        UPDATE bodegas_inventory
        SET current_stock = current_stock +
                CASE WHEN OLD.type = 'IN' THEN -OLD.quantity ELSE OLD.quantity END,
            updated_at = NOW()
        WHERE id = OLD.item_id;
        -- Aplicar efecto del nuevo valor
        UPDATE bodegas_inventory
        SET current_stock = current_stock +
                CASE WHEN NEW.type = 'IN' THEN NEW.quantity ELSE -NEW.quantity END,
            updated_at = NOW()
        WHERE id = NEW.item_id;
        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN
        UPDATE bodegas_inventory
        SET current_stock = current_stock +
                CASE WHEN OLD.type = 'IN' THEN -OLD.quantity ELSE OLD.quantity END,
            updated_at = NOW()
        WHERE id = OLD.item_id;
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_update_stock ON bodegas_transactions;
CREATE TRIGGER tr_update_stock
    AFTER INSERT OR UPDATE OR DELETE ON bodegas_transactions
    FOR EACH ROW
    EXECUTE FUNCTION update_inventory_stock();

-- =============================================================================
-- 5. ROW-LEVEL SECURITY (RLS)
-- =============================================================================

ALTER TABLE bodegas_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodegas_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodegas_list ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "bodegas_inventory_public_read" ON bodegas_inventory;
DROP POLICY IF EXISTS "bodegas_inventory_auth_all" ON bodegas_inventory;
DROP POLICY IF EXISTS "bodegas_transactions_public_read" ON bodegas_transactions;
DROP POLICY IF EXISTS "bodegas_transactions_auth_all" ON bodegas_transactions;
DROP POLICY IF EXISTS "bodegas_list_public_read" ON bodegas_list;
DROP POLICY IF EXISTS "bodegas_list_auth_all" ON bodegas_list;

-- Lectura publica (anon + authenticated)
CREATE POLICY "bodegas_inventory_public_read"
    ON bodegas_inventory FOR SELECT USING (true);

CREATE POLICY "bodegas_transactions_public_read"
    ON bodegas_transactions FOR SELECT USING (true);

CREATE POLICY "bodegas_list_public_read"
    ON bodegas_list FOR SELECT USING (true);

-- Escritura solo para autenticados
CREATE POLICY "bodegas_inventory_auth_all"
    ON bodegas_inventory FOR ALL
    TO authenticated
    USING (true) WITH CHECK (true);

CREATE POLICY "bodegas_transactions_auth_all"
    ON bodegas_transactions FOR ALL
    TO authenticated
    USING (true) WITH CHECK (true);

CREATE POLICY "bodegas_list_auth_all"
    ON bodegas_list FOR ALL
    TO authenticated
    USING (true) WITH CHECK (true);

-- =============================================================================
-- 6. DATOS INICIALES DE BODEGAS
-- =============================================================================

INSERT INTO bodegas_list (name, code) VALUES
    ('Bodega GDR 1 (MV)', 'MV'),
    ('Bodega GDR 1 (M&OPTAC #2)', 'M&OPTAC #2'),
    ('Bodega GDR 1 (OMV)', 'OMV'),
    ('Bodega GDR 2 (LSM & QC)', 'LSM & QC'),
    ('Bodega GDR 2 (C/QC&LSM)', 'C/QC&LSM'),
    ('Bodega GDR 2 (OMV)', 'OMV'),
    ('Bodega GDR 3 (M)', 'M'),
    ('Bodega GDR 3 (PTAC #2)', 'PTAC #2'),
    ('Bodega GDR 3 (MV)', 'MV'),
    ('Bodega GDR 4 (Container PTAC #2)', 'Container PTAC #2'),
    ('Bodega GDR 5 (M&OPTAC #2)', 'M&OPTAC #2'),
    ('Bodega GDR 5 (MV)', 'MV'),
    ('Sala de Induccion de GDR 6', 'GDR6'),
    ('Unidad de Monitoreo', 'MON'),
    ('Unidad de Operacion, Mantenimiento y Vigilancia', 'OMV-UNI'),
    ('Unidad de Construccion, Control de Calidad & Laboratorio', 'CCCL')
ON CONFLICT (name) DO NOTHING;

-- =============================================================================
-- 7. FUNCION AUXILIAR: Recalcular stock desde transacciones
-- =============================================================================

CREATE OR REPLACE FUNCTION recalculate_inventory_stock()
RETURNS void AS $$
DECLARE
    inv RECORD;
    calc_stock NUMERIC;
BEGIN
    FOR inv IN SELECT id, initial_stock FROM bodegas_inventory LOOP
        SELECT COALESCE(
            SUM(CASE WHEN type = 'IN' THEN quantity ELSE -quantity END),
            0
        ) INTO calc_stock
        FROM bodegas_transactions
        WHERE item_id = inv.id;

        UPDATE bodegas_inventory
        SET current_stock = inv.initial_stock + calc_stock,
            updated_at = NOW()
        WHERE id = inv.id;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 8. VERIFICACION
-- =============================================================================

SELECT 'bodegas_inventory columns:' as info;
SELECT column_name, data_type, is_nullable FROM information_schema.columns
WHERE table_name = 'bodegas_inventory' ORDER BY ordinal_position;

SELECT 'bodegas_transactions columns:' as info;
SELECT column_name, data_type, is_nullable FROM information_schema.columns
WHERE table_name = 'bodegas_transactions' ORDER BY ordinal_position;

SELECT 'bodegas_list:' as info;
SELECT id, name, code FROM bodegas_list ORDER BY name;

SELECT 'indices creados:' as info;
SELECT indexname, indexdef FROM pg_indexes
WHERE tablename LIKE 'bodegas_%' AND schemaname = 'public'
ORDER BY tablename, indexname;
