-- Tablas para el Módulo de Bodegas

-- 1. Tabla de Inventario (Artículos)
CREATE TABLE IF NOT EXISTS bodegas_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL,
    unit TEXT DEFAULT 'UND',
    category TEXT,
    current_stock NUMERIC DEFAULT 0,
    min_stock NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Transacciones (Ingresos y Egresos)
CREATE TABLE IF NOT EXISTS bodegas_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT REFERENCES bodegas_inventory(id) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('IN', 'OUT')), -- IN para Ingresos, OUT para Egresos
    quantity NUMERIC NOT NULL CHECK (quantity > 0),
    date DATE DEFAULT CURRENT_DATE,
    reason TEXT,
    created_by_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Función para actualizar el stock automáticamente
CREATE OR REPLACE FUNCTION update_inventory_stock()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        IF (NEW.type = 'IN') THEN
            UPDATE bodegas_inventory
            SET current_stock = current_stock + NEW.quantity,
                updated_at = NOW()
            WHERE id = NEW.item_id;
        ELSIF (NEW.type = 'OUT') THEN
            UPDATE bodegas_inventory
            SET current_stock = current_stock - NEW.quantity,
                updated_at = NOW()
            WHERE id = NEW.item_id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Trigger para ejecutar la función después de cada inserción en transacciones
DROP TRIGGER IF EXISTS tr_update_stock ON bodegas_transactions;
CREATE TRIGGER tr_update_stock
AFTER INSERT ON bodegas_transactions
FOR EACH ROW
EXECUTE FUNCTION update_inventory_stock();

-- 5. Políticas de Seguridad (RLS)
ALTER TABLE bodegas_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodegas_transactions ENABLE ROW LEVEL SECURITY;

-- Permitir lectura a todos los autenticados
CREATE POLICY "Enable read access for all users" ON bodegas_inventory FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON bodegas_transactions FOR SELECT USING (true);

-- Permitir inserción/actualización solo a administradores (o usuarios autorizados)
-- Nota: Aquí podrías restringir más según el rol, por ahora permitimos a todos los autenticados
-- para simplificar el desarrollo inicial, pero la UI bloqueará las acciones.
CREATE POLICY "Enable all for authenticated users" ON bodegas_inventory FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for authenticated users" ON bodegas_transactions FOR ALL USING (true) WITH CHECK (true);
