-- =============================================================================
-- REPARAR USUARIOS Y PERMISOS
-- =============================================================================
-- Ejecutar en SQL Editor de Supabase si hay problemas con usuarios
-- =============================================================================

-- 1. Asegurar que la tabla users tenga politica RLS correcta
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access Users" ON users;
CREATE POLICY "Public Access Users"
    ON users FOR ALL
    USING (true) WITH CHECK (true);

-- 2. Asegurar que user_permissions exista y tenga RLS correcto
CREATE TABLE IF NOT EXISTS user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    module TEXT NOT NULL,
    can_view BOOLEAN NOT NULL DEFAULT true,
    can_edit BOOLEAN NOT NULL DEFAULT false,
    can_delete BOOLEAN NOT NULL DEFAULT false,
    can_export BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, module)
);

ALTER TABLE user_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_permissions_admin_all" ON user_permissions;
CREATE POLICY "user_permissions_admin_all"
    ON user_permissions FOR ALL
    TO authenticated
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "user_permissions_public_read" ON user_permissions;
CREATE POLICY "user_permissions_public_read"
    ON user_permissions FOR SELECT
    USING (true);

-- 3. Asegurar que audit_log exista
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT NOT NULL,
    table_name TEXT NOT NULL,
    record_id BIGINT,
    action TEXT NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    old_values JSONB,
    new_values JSONB,
    changed_by TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    description TEXT
);

ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "audit_log_admin_all" ON audit_log;
CREATE POLICY "audit_log_admin_all"
    ON audit_log FOR ALL
    TO authenticated
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "audit_log_public_read" ON audit_log;
CREATE POLICY "audit_log_public_read"
    ON audit_log FOR SELECT
    USING (true);

-- 4. Funciones necesarias
CREATE OR REPLACE FUNCTION set_current_user(username TEXT)
RETURNS void AS $$
BEGIN
    PERFORM set_config('app.current_user', username, false);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_current_user()
RETURNS TEXT AS $$
BEGIN
    RETURN current_setting('app.current_user', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION create_default_permissions(p_user_id INTEGER, p_role TEXT)
RETURNS void AS $$
DECLARE
    v_modules TEXT[] := ARRAY['mantenimiento', 'pozos', 'bodegas'];
    v_mod TEXT;
BEGIN
    FOREACH v_mod IN ARRAY v_modules
    LOOP
        IF NOT EXISTS (SELECT 1 FROM user_permissions WHERE user_id = p_user_id AND module = v_mod) THEN
            IF p_role = 'admin' THEN
                INSERT INTO user_permissions (user_id, module, can_view, can_edit, can_delete, can_export)
                VALUES (p_user_id, v_mod, true, true, true, true);
            ELSIF p_role = 'user' THEN
                INSERT INTO user_permissions (user_id, module, can_view, can_edit, can_delete, can_export)
                VALUES (p_user_id, v_mod, true, false, false, true);
            ELSIF p_role = 'viewer' THEN
                INSERT INTO user_permissions (user_id, module, can_view, can_edit, can_delete, can_export)
                VALUES (p_user_id, v_mod, true, false, false, false);
            END IF;
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_user_permissions(p_user_id INTEGER)
RETURNS TABLE (
    module TEXT,
    can_view BOOLEAN,
    can_edit BOOLEAN,
    can_delete BOOLEAN,
    can_export BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT up.module, up.can_view, up.can_edit, up.can_delete, up.can_export
    FROM user_permissions up
    WHERE up.user_id = p_user_id
    ORDER BY up.module;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Trigger de auto-permisos (seguro, no falla si la tabla no existe)
CREATE OR REPLACE FUNCTION auto_create_user_permissions()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM create_default_permissions(NEW.id, NEW.role);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_auto_permissions ON users;
CREATE TRIGGER trg_auto_permissions
    AFTER INSERT ON users
    FOR EACH ROW EXECUTE FUNCTION auto_create_user_permissions();

-- 6. Crear permisos para usuarios existentes que no los tengan
DO $$
DECLARE
    u RECORD;
BEGIN
    FOR u IN SELECT id, role FROM users
    LOOP
        IF NOT EXISTS (SELECT 1 FROM user_permissions WHERE user_id = u.id) THEN
            PERFORM create_default_permissions(u.id, u.role);
        END IF;
    END LOOP;
END
$$;

-- 7. Funcion de auditoria
CREATE OR REPLACE FUNCTION audit_trigger_func()
RETURNS TRIGGER AS $$
DECLARE
    v_module TEXT;
    v_changed_by TEXT;
    v_description TEXT;
    v_old_json JSONB;
    v_new_json JSONB;
BEGIN
    v_module := CASE
        WHEN TG_TABLE_NAME = 'mantenimiento' THEN 'mantenimiento'
        WHEN TG_TABLE_NAME IN ('inspections', 'pump_records') THEN 'pozos'
        WHEN TG_TABLE_NAME LIKE 'bodegas_%' THEN 'bodegas'
        WHEN TG_TABLE_NAME = 'users' THEN 'auth'
        ELSE 'general'
    END;

    v_changed_by := current_setting('app.current_user', true);
    IF v_changed_by IS NULL THEN
        v_changed_by := 'system';
    END IF;

    IF TG_OP = 'INSERT' THEN
        v_new_json := to_jsonb(NEW);
        v_description := 'Nuevo registro en ' || TG_TABLE_NAME;
        IF TG_TABLE_NAME = 'mantenimiento' THEN
            v_description := 'Nuevo reporte: ' || COALESCE(NEW.tema, '');
        ELSIF TG_TABLE_NAME = 'bodegas_inventory' THEN
            v_description := 'Nuevo item: ' || COALESCE(NEW.code, '') || ' - ' || COALESCE(NEW.description, '');
        ELSIF TG_TABLE_NAME = 'bodegas_transactions' THEN
            v_description := 'Transaccion ' || COALESCE(NEW.type, '') || ' cantidad: ' || COALESCE(NEW.quantity, 0);
        ELSIF TG_TABLE_NAME = 'bodegas_list' THEN
            v_description := 'Nueva bodega: ' || COALESCE(NEW.name, '');
        ELSIF TG_TABLE_NAME = 'users' THEN
            v_description := 'Nuevo usuario: ' || COALESCE(NEW.username, '');
        ELSIF TG_TABLE_NAME = 'inspections' THEN
            v_description := 'Nueva inspeccion: ' || COALESCE(NEW.inspection_date::TEXT, '');
        ELSIF TG_TABLE_NAME = 'pump_records' THEN
            v_description := 'Nuevo registro bomba: ' || COALESCE(NEW.inspection_date::TEXT, '');
        END IF;

        INSERT INTO audit_log (module, table_name, record_id, action, old_values, new_values, changed_by, description)
        VALUES (v_module, TG_TABLE_NAME, NEW.id, 'INSERT', NULL, v_new_json, v_changed_by, v_description);
        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN
        v_old_json := to_jsonb(OLD);
        v_new_json := to_jsonb(NEW);
        v_description := 'Actualizacion en ' || TG_TABLE_NAME;

        IF TG_TABLE_NAME = 'mantenimiento' THEN
            v_description := 'Reporte actualizado: ' || COALESCE(NEW.tema, '');
        ELSIF TG_TABLE_NAME = 'bodegas_inventory' THEN
            v_description := 'Item actualizado: ' || COALESCE(NEW.code, '');
            IF OLD.current_stock IS DISTINCT FROM NEW.current_stock THEN
                v_description := v_description || ' | Stock: ' || OLD.current_stock || ' -> ' || NEW.current_stock;
            END IF;
        ELSIF TG_TABLE_NAME = 'bodegas_transactions' THEN
            v_description := 'Transaccion actualizada: id=' || NEW.id;
            IF OLD.quantity IS DISTINCT FROM NEW.quantity THEN
                v_description := v_description || ' | Cantidad: ' || OLD.quantity || ' -> ' || NEW.quantity;
            END IF;
        ELSIF TG_TABLE_NAME = 'users' THEN
            v_description := 'Usuario actualizado: ' || COALESCE(NEW.username, '');
            IF OLD.role IS DISTINCT FROM NEW.role THEN
                v_description := v_description || ' | Rol: ' || OLD.role || ' -> ' || NEW.role;
            END IF;
        ELSIF TG_TABLE_NAME = 'inspections' THEN
            v_description := 'Inspeccion actualizada: ' || COALESCE(NEW.inspection_date::TEXT, '');
        ELSIF TG_TABLE_NAME = 'pump_records' THEN
            v_description := 'Registro bomba actualizado: ' || COALESCE(NEW.inspection_date::TEXT, '');
        END IF;

        INSERT INTO audit_log (module, table_name, record_id, action, old_values, new_values, changed_by, description)
        VALUES (v_module, TG_TABLE_NAME, NEW.id, 'UPDATE', v_old_json, v_new_json, v_changed_by, v_description);
        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN
        v_old_json := to_jsonb(OLD);
        v_description := 'Registro eliminado de ' || TG_TABLE_NAME;

        IF TG_TABLE_NAME = 'mantenimiento' THEN
            v_description := 'Reporte eliminado: ' || COALESCE(OLD.tema, '');
        ELSIF TG_TABLE_NAME = 'bodegas_inventory' THEN
            v_description := 'Item eliminado: ' || COALESCE(OLD.code, '') || ' - ' || COALESCE(OLD.description, '');
        ELSIF TG_TABLE_NAME = 'bodegas_transactions' THEN
            v_description := 'Transaccion eliminada: id=' || OLD.id || ' tipo=' || OLD.type;
        ELSIF TG_TABLE_NAME = 'users' THEN
            v_description := 'Usuario eliminado: ' || COALESCE(OLD.username, '');
        ELSIF TG_TABLE_NAME = 'inspections' THEN
            v_description := 'Inspeccion eliminada: ' || COALESCE(OLD.inspection_date::TEXT, '');
        ELSIF TG_TABLE_NAME = 'pump_records' THEN
            v_description := 'Registro bomba eliminado: ' || COALESCE(OLD.inspection_date::TEXT, '');
        END IF;

        INSERT INTO audit_log (module, table_name, record_id, action, old_values, new_values, changed_by, description)
        VALUES (v_module, TG_TABLE_NAME, OLD.id, 'DELETE', v_old_json, NULL, v_changed_by, v_description);
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear triggers en cada tabla
DROP TRIGGER IF EXISTS audit_mantenimiento ON mantenimiento;
CREATE TRIGGER audit_mantenimiento AFTER INSERT OR UPDATE OR DELETE ON mantenimiento FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

DROP TRIGGER IF EXISTS audit_inspections ON inspections;
CREATE TRIGGER audit_inspections AFTER INSERT OR UPDATE OR DELETE ON inspections FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

DROP TRIGGER IF EXISTS audit_pump_records ON pump_records;
CREATE TRIGGER audit_pump_records AFTER INSERT OR UPDATE OR DELETE ON pump_records FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

DROP TRIGGER IF EXISTS audit_bodegas_inventory ON bodegas_inventory;
CREATE TRIGGER audit_bodegas_inventory AFTER INSERT OR UPDATE OR DELETE ON bodegas_inventory FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

DROP TRIGGER IF EXISTS audit_bodegas_transactions ON bodegas_transactions;
CREATE TRIGGER audit_bodegas_transactions AFTER INSERT OR UPDATE OR DELETE ON bodegas_transactions FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

DROP TRIGGER IF EXISTS audit_bodegas_list ON bodegas_list;
CREATE TRIGGER audit_bodegas_list AFTER INSERT OR UPDATE OR DELETE ON bodegas_list FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

DROP TRIGGER IF EXISTS audit_users ON users;
CREATE TRIGGER audit_users AFTER INSERT OR UPDATE OR DELETE ON users FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

-- 8. VERIFICACION
SELECT 'Usuarios existentes:' as info;
SELECT id, username, role FROM users ORDER BY username;

SELECT 'Permisos existentes:' as info;
SELECT * FROM v_user_permissions;
