-- =============================================================================
-- PERMISOS GRANULARES + AUDITORIA CENTRALIZADA (v1.0)
-- =============================================================================
-- Ejecutar en SQL Editor de Supabase
-- Crea tablas de permisos, auditoria, triggers automaticos, y RLS
-- =============================================================================

-- =============================================================================
-- 1. TABLA DE PERMISOS POR USUARIO
-- =============================================================================

CREATE TABLE IF NOT EXISTS user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    module TEXT NOT NULL,
    can_view BOOLEAN NOT NULL DEFAULT true,
    can_edit BOOLEAN NOT NULL DEFAULT false,
    can_delete BOOLEAN NOT NULL DEFAULT false,
    can_export BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, module)
);

CREATE INDEX IF NOT EXISTS idx_user_permissions_user_id ON user_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_permissions_module ON user_permissions(module);

-- =============================================================================
-- 2. TABLA DE AUDITORIA CENTRALIZADA
-- =============================================================================

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT NOT NULL,
    table_name TEXT NOT NULL,
    record_id BIGINT,
    action TEXT NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    old_values JSONB,
    new_values JSONB,
    changed_by TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    description TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_log_module ON audit_log(module);
CREATE INDEX IF NOT EXISTS idx_audit_log_table ON audit_log(table_name);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_by ON audit_log(changed_by);
CREATE INDEX IF NOT EXISTS idx_audit_log_changed_at ON audit_log(changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_module_action ON audit_log(module, action);

-- =============================================================================
-- 3. FUNCION: SET CURRENT USER (para capturar quien hace cambios)
-- =============================================================================

-- Variable de sesion para capturar el usuario actual
-- Los triggers la leen automaticamente

CREATE OR REPLACE FUNCTION set_current_user(username TEXT)
RETURNS void AS $$
BEGIN
    PERFORM set_config('app.current_user', username, false);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_current_user()
RETURNS TEXT AS $$
BEGIN
    RETURN current_setting('app.current_user', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- 4. TRIGGERS DE AUDITORIA AUTOMATICA
-- =============================================================================

-- Funcion generica de auditoria
CREATE OR REPLACE FUNCTION audit_trigger_func()
RETURNS TRIGGER AS $$
DECLARE
    v_module TEXT;
    v_changed_by TEXT;
    v_description TEXT;
    v_old_json JSONB;
    v_new_json JSONB;
BEGIN
    -- Determinar modulo basado en la tabla
    v_module := CASE
        WHEN TG_TABLE_NAME = 'mantenimiento' THEN 'mantenimiento'
        WHEN TG_TABLE_NAME IN ('inspections', 'pump_records') THEN 'pozos'
        WHEN TG_TABLE_NAME LIKE 'bodegas_%' THEN 'bodegas'
        WHEN TG_TABLE_NAME = 'users' THEN 'auth'
        ELSE 'general'
    END;

    -- Obtener usuario actual
    v_changed_by := current_setting('app.current_user', true);
    IF v_changed_by IS NULL THEN
        v_changed_by := 'system';
    END IF;

    -- Generar JSON y descripcion segun la accion
    IF TG_OP = 'INSERT' THEN
        v_new_json := to_jsonb(NEW);
        v_description := 'Nuevo registro en ' || TG_TABLE_NAME;
        -- Intentar obtener descripcion significativa
        IF TG_TABLE_NAME = 'mantenimiento' THEN
            v_description := 'Nuevo reporte: ' || COALESCE(NEW.tema, '');
        ELSIF TG_TABLE_NAME = 'bodegas_inventory' THEN
            v_description := 'Nuevo item: ' || COALESCE(NEW.code, '') || ' - ' || COALESCE(NEW.description, '');
        ELSIF TG_TABLE_NAME = 'bodegas_transactions' THEN
            v_description := 'Transaccion ' || COALESCE(NEW.type, '') || ' cantidad: ' || COALESCE(NEW.quantity, 0);
        ELSIF TG_TABLE_NAME = 'bodegas_list' THEN
            v_description := 'Nueva bodega: ' || COALESCE(NEW.name, '');
        ELSIF TG_TABLE_NAME = 'users' THEN
            v_description := 'Nuevo usuario: ' || COALESCE(NEW.username, '');
        ELSIF TG_TABLE_NAME = 'inspections' THEN
            v_description := 'Nueva inspeccion: ' || COALESCE(NEW.inspection_date::TEXT, '');
        ELSIF TG_TABLE_NAME = 'pump_records' THEN
            v_description := 'Nuevo registro bomba: ' || COALESCE(NEW.inspection_date::TEXT, '');
        END IF;

        INSERT INTO audit_log (module, table_name, record_id, action, old_values, new_values, changed_by, description)
        VALUES (v_module, TG_TABLE_NAME, NEW.id, 'INSERT', NULL, v_new_json, v_changed_by, v_description);

        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN
        v_old_json := to_jsonb(OLD);
        v_new_json := to_jsonb(NEW);
        v_description := 'Actualizacion en ' || TG_TABLE_NAME;

        IF TG_TABLE_NAME = 'mantenimiento' THEN
            v_description := 'Reporte actualizado: ' || COALESCE(NEW.tema, '');
        ELSIF TG_TABLE_NAME = 'bodegas_inventory' THEN
            v_description := 'Item actualizado: ' || COALESCE(NEW.code, '');
            -- Detectar cambio de stock especificamente
            IF OLD.current_stock IS DISTINCT FROM NEW.current_stock THEN
                v_description := v_description || ' | Stock: ' || OLD.current_stock || ' -> ' || NEW.current_stock;
            END IF;
        ELSIF TG_TABLE_NAME = 'bodegas_transactions' THEN
            v_description := 'Transaccion actualizada: id=' || NEW.id;
            IF OLD.quantity IS DISTINCT FROM NEW.quantity THEN
                v_description := v_description || ' | Cantidad: ' || OLD.quantity || ' -> ' || NEW.quantity;
            END IF;
        ELSIF TG_TABLE_NAME = 'users' THEN
            v_description := 'Usuario actualizado: ' || COALESCE(NEW.username, '');
            IF OLD.role IS DISTINCT FROM NEW.role THEN
                v_description := v_description || ' | Rol: ' || OLD.role || ' -> ' || NEW.role;
            END IF;
        ELSIF TG_TABLE_NAME = 'inspections' THEN
            v_description := 'Inspeccion actualizada: ' || COALESCE(NEW.inspection_date::TEXT, '');
        ELSIF TG_TABLE_NAME = 'pump_records' THEN
            v_description := 'Registro bomba actualizado: ' || COALESCE(NEW.inspection_date::TEXT, '');
        END IF;

        INSERT INTO audit_log (module, table_name, record_id, action, old_values, new_values, changed_by, description)
        VALUES (v_module, TG_TABLE_NAME, NEW.id, 'UPDATE', v_old_json, v_new_json, v_changed_by, v_description);

        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN
        v_old_json := to_jsonb(OLD);
        v_description := 'Registro eliminado de ' || TG_TABLE_NAME;

        IF TG_TABLE_NAME = 'mantenimiento' THEN
            v_description := 'Reporte eliminado: ' || COALESCE(OLD.tema, '');
        ELSIF TG_TABLE_NAME = 'bodegas_inventory' THEN
            v_description := 'Item eliminado: ' || COALESCE(OLD.code, '') || ' - ' || COALESCE(OLD.description, '');
        ELSIF TG_TABLE_NAME = 'bodegas_transactions' THEN
            v_description := 'Transaccion eliminada: id=' || OLD.id || ' tipo=' || OLD.type;
        ELSIF TG_TABLE_NAME = 'users' THEN
            v_description := 'Usuario eliminado: ' || COALESCE(OLD.username, '');
        ELSIF TG_TABLE_NAME = 'inspections' THEN
            v_description := 'Inspeccion eliminada: ' || COALESCE(OLD.inspection_date::TEXT, '');
        ELSIF TG_TABLE_NAME = 'pump_records' THEN
            v_description := 'Registro bomba eliminado: ' || COALESCE(OLD.inspection_date::TEXT, '');
        END IF;

        INSERT INTO audit_log (module, table_name, record_id, action, old_values, new_values, changed_by, description)
        VALUES (v_module, TG_TABLE_NAME, OLD.id, 'DELETE', v_old_json, NULL, v_changed_by, v_description);

        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear triggers en cada tabla de datos

-- Mantenimiento
DROP TRIGGER IF EXISTS audit_mantenimiento ON mantenimiento;
CREATE TRIGGER audit_mantenimiento
    AFTER INSERT OR UPDATE OR DELETE ON mantenimiento
    FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

-- Pozos
DROP TRIGGER IF EXISTS audit_inspections ON inspections;
CREATE TRIGGER audit_inspections
    AFTER INSERT OR UPDATE OR DELETE ON inspections
    FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

DROP TRIGGER IF EXISTS audit_pump_records ON pump_records;
CREATE TRIGGER audit_pump_records
    AFTER INSERT OR UPDATE OR DELETE ON pump_records
    FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

-- Bodegas
DROP TRIGGER IF EXISTS audit_bodegas_inventory ON bodegas_inventory;
CREATE TRIGGER audit_bodegas_inventory
    AFTER INSERT OR UPDATE OR DELETE ON bodegas_inventory
    FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

DROP TRIGGER IF EXISTS audit_bodegas_transactions ON bodegas_transactions;
CREATE TRIGGER audit_bodegas_transactions
    AFTER INSERT OR UPDATE OR DELETE ON bodegas_transactions
    FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

DROP TRIGGER IF EXISTS audit_bodegas_list ON bodegas_list;
CREATE TRIGGER audit_bodegas_list
    AFTER INSERT OR UPDATE OR DELETE ON bodegas_list
    FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

-- Auth (users)
DROP TRIGGER IF EXISTS audit_users ON users;
CREATE TRIGGER audit_users
    AFTER INSERT OR UPDATE OR DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION audit_trigger_func();

-- =============================================================================
-- 5. ROW-LEVEL SECURITY (RLS)
-- =============================================================================

-- Asegurar politica de users (no modificar la existente, solo verificar)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'Public Access Users'
    ) THEN
        ALTER TABLE users ENABLE ROW LEVEL SECURITY;
        CREATE POLICY "Public Access Users" ON users FOR ALL USING (true) WITH CHECK (true);
    END IF;
END
$$;

-- user_permissions
ALTER TABLE user_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_permissions_admin_all" ON user_permissions;
CREATE POLICY "user_permissions_admin_all"
    ON user_permissions FOR ALL
    TO authenticated
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "user_permissions_public_read" ON user_permissions;
CREATE POLICY "user_permissions_public_read"
    ON user_permissions FOR SELECT
    USING (true);

-- audit_log (solo lectura para todos, escritura solo via triggers)
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "audit_log_admin_all" ON audit_log;
CREATE POLICY "audit_log_admin_all"
    ON audit_log FOR ALL
    TO authenticated
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "audit_log_public_read" ON audit_log;
CREATE POLICY "audit_log_public_read"
    ON audit_log FOR SELECT
    USING (true);

-- =============================================================================
-- 6. FUNCION: CREAR PERMISOS POR DEFECTO
-- =============================================================================

CREATE OR REPLACE FUNCTION create_default_permissions(p_user_id INTEGER, p_role TEXT)
RETURNS void AS $$
DECLARE
    v_modules TEXT[] := ARRAY['mantenimiento', 'pozos', 'bodegas'];
    v_mod TEXT;
BEGIN
    FOREACH v_mod IN ARRAY v_modules
    LOOP
        -- Evitar duplicados
        IF NOT EXISTS (SELECT 1 FROM user_permissions WHERE user_id = p_user_id AND module = v_mod) THEN
            IF p_role = 'admin' THEN
                INSERT INTO user_permissions (user_id, module, can_view, can_edit, can_delete, can_export)
                VALUES (p_user_id, v_mod, true, true, true, true);
            ELSIF p_role = 'user' THEN
                INSERT INTO user_permissions (user_id, module, can_view, can_edit, can_delete, can_export)
                VALUES (p_user_id, v_mod, true, false, false, true);
            ELSIF p_role = 'viewer' THEN
                INSERT INTO user_permissions (user_id, module, can_view, can_edit, can_delete, can_export)
                VALUES (p_user_id, v_mod, true, false, false, false);
            END IF;
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- 7. TRIGGER: Crear permisos automaticamente al crear usuario
-- =============================================================================

CREATE OR REPLACE FUNCTION auto_create_user_permissions()
RETURNS TRIGGER AS $$
BEGIN
    -- Solo crear permisos si la tabla existe
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_permissions') THEN
        PERFORM create_default_permissions(NEW.id, NEW.role);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_auto_permissions ON users;
CREATE TRIGGER trg_auto_permissions
    AFTER INSERT ON users
    FOR EACH ROW EXECUTE FUNCTION auto_create_user_permissions();

-- =============================================================================
-- 8. CREAR PERMISOS PARA USUARIOS EXISTENTES
-- =============================================================================

DO $$
DECLARE
    u RECORD;
BEGIN
    FOR u IN SELECT id, role FROM users
    LOOP
        PERFORM create_default_permissions(u.id, u.role);
    END LOOP;
END
$$;

-- =============================================================================
-- 9. VISTA: Permisos con info de usuario
-- =============================================================================

CREATE OR REPLACE VIEW v_user_permissions AS
SELECT
    up.id,
    up.user_id,
    u.username,
    u.role,
    up.module,
    up.can_view,
    up.can_edit,
    up.can_delete,
    up.can_export,
    up.created_at
FROM user_permissions up
JOIN users u ON u.id = up.user_id
ORDER BY u.username, up.module;

-- =============================================================================
-- 10. FUNCION: Obtener permisos de un usuario
-- =============================================================================

CREATE OR REPLACE FUNCTION get_user_permissions(p_user_id INTEGER)
RETURNS TABLE (
    module TEXT,
    can_view BOOLEAN,
    can_edit BOOLEAN,
    can_delete BOOLEAN,
    can_export BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT up.module, up.can_view, up.can_edit, up.can_delete, up.can_export
    FROM user_permissions up
    WHERE up.user_id = p_user_id
    ORDER BY up.module;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- 11. VERIFICACION
-- =============================================================================

SELECT 'Tablas creadas:' as info;
SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename IN ('user_permissions', 'audit_log') ORDER BY tablename;

SELECT 'Triggers de auditoria:' as info;
SELECT trigger_name, event_object_table, event_manipulation
FROM information_schema.triggers
WHERE trigger_name LIKE 'audit_%'
ORDER BY event_object_table, event_manipulation;

SELECT 'Permisos existentes:' as info;
SELECT * FROM v_user_permissions;

SELECT 'Funciones disponibles:' as info;
SELECT routine_name FROM information_schema.routines
WHERE routine_schema = 'public' AND routine_name IN ('set_current_user', 'get_current_user', 'create_default_permissions', 'get_user_permissions');
